version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.8.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run unit tests
          command: |
      - run:
          name: python go
          command:
            python -m pytest
      - run:
          name: python install
          command:

            from jinja2.utils import markupsafe 

            markupsafe.Markup()
            Markup('')
workflows:
  build_test:
    jobs:
      - run_tests
      
